### ISSUE TITLE
broken installation

### ISSUE THREAD

**Issue by lironess** [wdavidw/node-hbase#35]
Tried to install this on 2 different computers (Macbook Pro with Yosemite) and got this errors:
```
✗ npm install hbase --save
```
```shell
npm http request GET https://registry.npmjs.org/hbase
npm http 200 https://registry.npmjs.org/hbase
npm http fetch GET https://registry.npmjs.org/hbase/-/hbase-0.2.2.tgz
npm http fetch 200 https://registry.npmjs.org/hbase/-/hbase-0.2.2.tgz
npm http request GET https://registry.npmjs.org/krb5
npm http 304 https://registry.npmjs.org/krb5

> krb5@0.0.3 preinstall /Users/lironshmuel/Workspace/playground/node_modules/hbase/node_modules/krb5
> coffee -b -o lib src


> krb5@0.0.3 install /Users/lironshmuel/Workspace/playground/node_modules/hbase/node_modules/krb5
> node-gyp rebuild

  CXX(target) Release/obj.target/krb5/src/krb5.o
In file included from ../src/krb5.cc:1:
../src/krb5.h:58:79: error: no type named 'AccessorInfo' in namespace 'v8'
  static v8::Handle<v8::Value> getToken(Local<v8::String> property, const v8::AccessorInfo& info);
                                                                          ~~~~^
../src/krb5.h:59:77: error: no type named 'AccessorInfo' in namespace 'v8'
  static v8::Handle<v8::Value> getErr(Local<v8::String> property, const v8::AccessorInfo& info);
                                                                        ~~~~^
../src/krb5.h:62:39: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<Value> Init(const v8::Arguments& args);
                                      ^~~~~~~~~~~~~
                                      v8::internal::Arguments
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/krb5.cc:1:
../src/krb5.h:63:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<Value> ByPassword(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/krb5.cc:1:
../src/krb5.h:64:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<Value> ByKeyTab(const v8::Arguments& args);
                                          ^~~~~~~~~~~~~
                                          v8::internal::Arguments
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/krb5.cc:1:
../src/krb5.h:65:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<Value> GenToken(const v8::Arguments& args);
                                          ^~~~~~~~~~~~~
                                          v8::internal::Arguments
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/krb5.cc:1:
../src/krb5.h:66:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<Value> Destroy(const v8::Arguments& args);
                                         ^~~~~~~~~~~~~
                                         v8::internal::Arguments
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/krb5.cc:1:
../src/krb5.h:68:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<Value> InitSync(const v8::Arguments& args);
                                          ^~~~~~~~~~~~~
                                          v8::internal::Arguments
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/krb5.cc:1:
../src/krb5.h:69:49: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<Value> ByPasswordSync(const v8::Arguments& args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/krb5.cc:1:
../src/krb5.h:70:47: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<Value> ByKeyTabSync(const v8::Arguments& args);
                                              ^~~~~~~~~~~~~
                                              v8::internal::Arguments
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/krb5.cc:1:
../src/krb5.h:71:47: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<Value> GenTokenSync(const v8::Arguments& args);
                                              ^~~~~~~~~~~~~
                                              v8::internal::Arguments
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/krb5.cc:1:
../src/krb5.h:72:46: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<Value> DestroySync(const v8::Arguments& args);
                                             ^~~~~~~~~~~~~
                                             v8::internal::Arguments
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/krb5.cc:1:
../src/krb5.h:74:38: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<Value> New(const Arguments& args);
                                     ^~~~~~~~~
                                     v8::internal::Arguments
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/krb5.cc:1:
../src/krb5.h:84:17: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  UvBaton(const v8::Arguments& args);
                ^~~~~~~~~~~~~
                v8::internal::Arguments
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/krb5.cc:26:15: warning: 'krb5_cc_default' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  this->err = krb5_cc_default(this->context, &this->cache);
              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1736:31: note: 'krb5_cc_default' has been explicitly
      marked deprecated here
krb5_error_code KRB5_CALLCONV krb5_cc_default
                              ^
../src/krb5.cc:30:14: warning: 'krb5_cc_get_name' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  if(!exists(krb5_cc_get_name(this->context, this->cache))){
             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1286:1: note: 'krb5_cc_get_name' has been explicitly
      marked deprecated here
krb5_cc_get_name (krb5_context context, krb5_ccache cache) KERBEROS_APPLE_DEPRECATED("use GSS.framework");
^
../src/krb5.cc:31:17: warning: 'krb5_cc_initialize' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    this->err = krb5_cc_initialize(this->context, this->cache, this->client_principal);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1292:1: note: 'krb5_cc_initialize' has been explicitly
      marked deprecated here
krb5_cc_initialize(krb5_context context, krb5_ccache cache,
^
../src/krb5.cc:42:17: warning: 'krb5_cc_resolve' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    this->err = krb5_cc_resolve(this->context, name, &cache);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1728:31: note: 'krb5_cc_resolve' has been explicitly
      marked deprecated here
krb5_error_code KRB5_CALLCONV krb5_cc_resolve
                              ^
../src/krb5.cc:46:17: warning: 'krb5_cc_default' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    this->err = krb5_cc_default(this->context, &cache);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1736:31: note: 'krb5_cc_default' has been explicitly
      marked deprecated here
krb5_error_code KRB5_CALLCONV krb5_cc_default
                              ^
../src/krb5.cc:49:15: warning: 'krb5_cc_destroy' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  this->err = krb5_cc_destroy(this->context, cache);
              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1296:1: note: 'krb5_cc_destroy' has been explicitly
      marked deprecated here
krb5_cc_destroy (krb5_context context, krb5_ccache cache) KERBEROS_APPLE_DEPRECATED("use GSS.framework");
^
../src/krb5.cc:56:15: warning: 'krb5_init_secure_context' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  this->err = krb5_init_secure_context(&this->context);
              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1454:31: note: 'krb5_init_secure_context' has been
      explicitly marked deprecated here
krb5_error_code KRB5_CALLCONV krb5_init_secure_context
                              ^
../src/krb5.cc:69:5: warning: 'krb5_cc_close' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    krb5_cc_close(this->context, this->cache);
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1299:1: note: 'krb5_cc_close' has been explicitly marked
      deprecated here
krb5_cc_close (krb5_context context, krb5_ccache cache) KERBEROS_APPLE_DEPRECATED("use GSS.framework");
^
../src/krb5.cc:71:5: warning: 'krb5_free_principal' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    krb5_free_principal(this->context,this->client_principal);
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1760:20: note: 'krb5_free_principal' has been explicitly
      marked deprecated here
void KRB5_CALLCONV krb5_free_principal
                   ^
../src/krb5.cc:73:5: warning: 'krb5_free_context' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    krb5_free_context(this->context);
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1456:20: note: 'krb5_free_context' has been explicitly
      marked deprecated here
void KRB5_CALLCONV krb5_free_context
                   ^
../src/krb5.cc:85:10: warning: 'krb5_get_error_message' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  return krb5_get_error_message(this->context, this->err);
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:2447:1: note: 'krb5_get_error_message' has been
      explicitly marked deprecated here
krb5_get_error_message (krb5_context, krb5_error_code) KERBEROS_APPLE_DEPRECATED("use GSS.framework");
^
../src/krb5.cc:97:21: warning: 'krb5_kt_resolve' is deprecated: use GSS.framework [-Wdeprecated-declarations]
        this->err = krb5_kt_resolve(this->context, kt, &keytab);
                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1698:31: note: 'krb5_kt_resolve' has been explicitly
      marked deprecated here
krb5_error_code KRB5_CALLCONV krb5_kt_resolve
                              ^
../src/krb5.cc:100:21: warning: 'krb5_kt_default' is deprecated: use GSS.framework [-Wdeprecated-declarations]
        this->err = krb5_kt_default(this->context,&keytab);
                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1706:31: note: 'krb5_kt_default' has been explicitly
      marked deprecated here
krb5_error_code KRB5_CALLCONV krb5_kt_default
                              ^
../src/krb5.cc:105:19: warning: 'krb5_kt_default' is deprecated: use GSS.framework [-Wdeprecated-declarations]
      this->err = krb5_kt_default(this->context,&keytab);
                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1706:31: note: 'krb5_kt_default' has been explicitly
      marked deprecated here
krb5_error_code KRB5_CALLCONV krb5_kt_default
                              ^
../src/krb5.cc:110:17: warning: 'krb5_get_init_creds_keytab' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    this->err = krb5_get_init_creds_keytab(context, cred, client_principal, keytab, 0, NULL, NULL);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:2337:1: note: 'krb5_get_init_creds_keytab' has been
      explicitly marked deprecated here
krb5_get_init_creds_keytab
^
../src/krb5.cc:114:17: warning: 'krb5_verify_init_creds' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    this->err = krb5_verify_init_creds(this->context,this->cred,NULL, NULL, NULL, NULL);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:2362:1: note: 'krb5_verify_init_creds' has been
      explicitly marked deprecated here
krb5_verify_init_creds
^
../src/krb5.cc:119:17: warning: 'krb5_cc_store_cred' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    this->err = krb5_cc_store_cred(this->context, this->cache, this->cred);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1302:1: note: 'krb5_cc_store_cred' has been explicitly
      marked deprecated here
krb5_cc_store_cred (krb5_context context, krb5_ccache cache,
^
../src/krb5.cc:132:17: warning: 'krb5_get_init_creds_password' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    this->err = krb5_get_init_creds_password(this->context,this->cred,this->client_principal,password, NULL, NULL, 0, NULL, NULL);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:2325:1: note: 'krb5_get_init_creds_password' has been
      explicitly marked deprecated here
krb5_get_init_creds_password
^
../src/krb5.cc:137:17: warning: 'krb5_cc_store_cred' is deprecated: use GSS.framework [-Wdeprecated-declarations]
    this->err = krb5_cc_store_cred(this->context, this->cache, this->cred);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/krb5/krb5.h:1302:1: note: 'krb5_cc_store_cred' has been explicitly
      marked deprecated here
krb5_cc_store_cred (krb5_context context, krb5_ccache cache,
^
../src/krb5.cc:152:7: warning: 'gss_import_name' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  ret=gss_import_name((OM_uint32*)&this->err, &service,GSS_C_NT_HOSTBASED_SERVICE, desired_name);
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/gssapi/gssapi.h:586:1: note: 'gss_import_name' has been explicitly
      marked deprecated here
gss_import_name(
^
../src/krb5.cc:171:9: warning: 'gss_init_sec_context' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  err = gss_init_sec_context((OM_uint32*)&this->err,
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/gssapi/gssapi.h:461:1: note: 'gss_init_sec_context' has been
      explicitly marked deprecated here
gss_init_sec_context(
^
../src/krb5.cc:191:3: warning: 'gss_release_name' is deprecated: use GSS.framework [-Wdeprecated-declarations]
  gss_release_name((OM_uint32*)&this->err, &target_name);
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/gssapi/gssapi.h:593:1: note: 'gss_release_name' has been explicitly
      marked deprecated here
gss_release_name(
^
../src/krb5.cc:198:27: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
UvBaton<T>::UvBaton(const v8::Arguments& args){
                          ^~~~~~~~~~~~~
                          v8::internal::Arguments
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/krb5.cc:200:51: error: member access into incomplete type 'const v8::internal::Arguments'
  this->wrapper = node::ObjectWrap::Unwrap<T>(args.This());
                                                  ^
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/krb5.cc:201:22: error: member access into incomplete type 'const v8::internal::Arguments'
  this->length = args.Length()-1;
                     ^
/Users/lironshmuel/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/krb5.cc:202:73: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  this->callback = Persistent<Function>::New(Handle<Function>::Cast(args[0]));
                                                                    ~~~~^~
../src/krb5.cc:205:38: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    v8::String::Utf8Value params(args[i+1]->ToString());
                                 ~~~~^~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
22 warnings and 20 errors generated.
make: *** [Release/obj.target/krb5/src/krb5.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lironshmuel/Workspace/playground/node_modules/hbase/node_modules/krb5
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing krb5@0.0.3
hbase@0.2.2 node_modules/hbase
```

**Comment by wdavidw** [comment]
do u need kerberos? If not, the package 'krb5' is marked as optional so add '--no-optional' to your npm command. Otherwise, follow instructions on the krb5 readme to install it on osx. If you have time, update the readme of this project to make it more clear to our fellow hbase users.
