### ISSUE TITLE
client.getVersion is not a function

### ISSUE THREAD

**Issue by sohimankotia** [wdavidw/node-hbase#39]
Hi I have installed hbase module with  sudo npm install hbase --no-optional .

I was running follwing code 

var hbase = require('hbase');

 var client = new hbase.Client({
 host: 'myIP',
 port: 8080
 });

 console.log("Got Client"+ client)

 client.getVersion( function( error, version ){
 console.log( version );
 } );

Rest service is running on host and port . But getting following error 

client.getVersion is not a function
    at Object.<anonymous> (/home/sohanvir/Desktop/hbase-node.js:10:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by wdavidw** [comment]
Please take a look at the [client test](https://github.com/wdavidw/node-hbase/blob/master/test/client.coffee#L8-L16). I've fixed the documentation but I wont be able to update its online version for now.

**Comment by sohimankotia** [comment]
Thanks for your fast response .. It working .
